# Generated by Django 5.1 on 2024-09-04 12:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('CustomerApi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TaskDetails', models.CharField(max_length=200, null=True)),
                ('DueDate', models.DateField(null=True)),
                ('TimeIn', models.TimeField(null=True)),
                ('TimeOut', models.TimeField(null=True)),
                ('NatureOfWork', models.CharField(max_length=200, null=True)),
                ('UsedItems', models.CharField(max_length=200, null=True)),
                ('REMARKS', models.CharField(choices=[('Pending', 'Pending'), ('On-Progress', 'On-Progress'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled'), ('On Hold', 'On Hold'), ('Closed', 'Closed'), ('ReOpened', 'ReOpened')], default='Pending', max_length=20, null=True)),
                ('OrganisationName', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='CustomerApi.customers')),
            ],
        ),
    ]
