# Generated by Django 5.1 on 2024-09-07 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Taskapi', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='AdditionalTask',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='FreightCharges',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='ReturnedItems',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='REMARKS',
            field=models.CharField(choices=[('Pending', 'Pending'), ('On-Progress', 'On-Progress'), ('Pratially Completed', 'Pratially Completed'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled'), ('On Hold', 'On Hold'), ('Closed', 'Closed'), ('ReOpened', 'ReOpened')], default='Pending', max_length=20, null=True),
        ),
    ]
