# Generated by Django 5.1 on 2024-09-07 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Taskapi', '0003_task_additionaltask_task_freightcharges_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='AdditionalTask',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=3, null=True),
        ),
    ]
