# Generated by Django 5.1 on 2024-09-08 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Taskapi', '0004_alter_task_additionaltask'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='username',
        ),
        migrations.AddField(
            model_name='task',
            name='user_ids',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
