# Generated by Django 5.1 on 2024-09-09 06:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Taskapi', '0005_remove_task_username_task_user_ids'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='AdditionalTask',
        ),
        migrations.RemoveField(
            model_name='task',
            name='FreightCharges',
        ),
        migrations.RemoveField(
            model_name='task',
            name='NatureOfWork',
        ),
        migrations.RemoveField(
            model_name='task',
            name='REMARKS',
        ),
        migrations.RemoveField(
            model_name='task',
            name='ReturnedItems',
        ),
        migrations.RemoveField(
            model_name='task',
            name='TimeIn',
        ),
        migrations.RemoveField(
            model_name='task',
            name='TimeOut',
        ),
        migrations.RemoveField(
            model_name='task',
            name='UsedItems',
        ),
        migrations.RemoveField(
            model_name='task',
            name='user_ids',
        ),
        migrations.AddField(
            model_name='task',
            name='SetPriority',
            field=models.CharField(choices=[('High', 'High'), ('Low', 'Low'), ('Medium', 'Medium')], default='Medium', max_length=10),
        ),
        migrations.AddField(
            model_name='task',
            name='username',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Task_Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TimeIn', models.TimeField(null=True)),
                ('FreightCharges', models.IntegerField(null=True)),
                ('TimeOut', models.TimeField(null=True)),
                ('NatureOfWork', models.CharField(max_length=200, null=True)),
                ('UsedItems', models.CharField(max_length=200, null=True)),
                ('ReturnedItems', models.CharField(max_length=200, null=True)),
                ('AdditionalTask', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=5)),
                ('REMARKS', models.CharField(choices=[('Pending', 'Pending'), ('On-Progress', 'On-Progress'), ('Partially Completed', 'Partially Completed'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled'), ('On Hold', 'On Hold'), ('Closed', 'Closed'), ('ReOpened', 'ReOpened')], default='Pending', max_length=20, null=True)),
                ('task', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task_details', to='Taskapi.task')),
            ],
        ),
    ]
