# Generated by Django 5.1 on 2024-09-09 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Taskapi', '0006_remove_task_additionaltask_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task_details',
            name='FreightCharges',
        ),
        migrations.RemoveField(
            model_name='task_details',
            name='ReturnedItems',
        ),
        migrations.RemoveField(
            model_name='task_details',
            name='TimeIn',
        ),
        migrations.RemoveField(
            model_name='task_details',
            name='TimeOut',
        ),
        migrations.RemoveField(
            model_name='task_details',
            name='UsedItems',
        ),
        migrations.AddField(
            model_name='task',
            name='FreightCharges',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='ReturnedItems',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='TimeIn',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='TimeOut',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='UsedItems',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
