# Generated by Django 5.1 on 2024-09-09 09:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Taskapi', '0007_remove_task_details_freightcharges_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='FreightCharges',
        ),
        migrations.RemoveField(
            model_name='task',
            name='ReturnedItems',
        ),
        migrations.RemoveField(
            model_name='task',
            name='TimeIn',
        ),
        migrations.RemoveField(
            model_name='task',
            name='TimeOut',
        ),
        migrations.RemoveField(
            model_name='task',
            name='UsedItems',
        ),
        migrations.AddField(
            model_name='task_details',
            name='FreightCharges',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='task_details',
            name='ReturnedItems',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='task_details',
            name='TimeIn',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='task_details',
            name='TimeOut',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='task_details',
            name='UsedItems',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.RemoveField(
            model_name='task',
            name='username',
        ),
        migrations.AddField(
            model_name='task',
            name='username',
            field=models.ManyToManyField(related_name='tasks', to=settings.AUTH_USER_MODEL),
        ),
    ]
